version: '3.3'

services:
    database:
        image: 'mysql:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: ''
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
            - "3310:3306"
        volumes:
            - ./docker/database/data:/var/lib/mysql

    web:
        build:
            context: ./docker/php-fpm
        depends_on:
            - database
        environment: []
#            - APP_ENV=${APP_ENV}
#            - APP_SECRET=${APP_SECRET}
#            - DATABASE_URL=mysql://root:@database:3306/main
        volumes:
            - ./:/var/www:cached
            - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini

    nginx:
        build:
            context: ./docker/nginx
        volumes:
            - ./:/var/www:cached
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites/:/etc/nginx/sites-available
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./var/log:/var/log
        depends_on:
            - web
        ports:
            - "8089:80"
